### ISSUE TITLE
Update to Polkadot version 1.1.0

### ISSUE THREAD

**Issue by gianfra-t** [pendulum-chain/Zenlink-DEX-Module#4]
Related to [tasks/#306](https://github.com/pendulum-chain/tasks/issues/306)

To perform the upgrade of Pendulum to Polkadot release `1.1.0` we need to update Zenlink to [polkadot-sdk release v1.1.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.1.0).

This version is not currently supported by Zenlink (highest is [0.9.42](https://github.com/zenlinkpro/Zenlink-DEX-Module/tree/polkadot-v0.9.42)) so we need to maintain it ourselves.

**Comment by ebma** [comment]
We can simply point to this branch though https://github.com/bifrost-finance/Zenlink-DEX-Module/tree/release-polkadot-v1.1.0, right?

**Comment by gianfra-t** [comment]
Yes! That's nice, I almost thought we had to branch it ourselves since I didn't get to the point of looking for alternatives. I don't think there is a point to this ticket then.

**Comment by ebma** [comment]
Great, let's close it then 🙏
